### PR TITLE
Initial header and initial detailsView

### PR DESCRIPTION
**Pull request by Anthial**
Navigation through header, initialises work on #16! 
Also removes most of the previous CSS!

### CODE REVIEW

**Comment by Anthial** [comment]
Say goodbye to the nice and centred App.tsx 😄

**Review by adrian-jonsson-sjoedin — APPROVED** [review]
I think it works as a first draft but I still think it needs some styling work

**Comment by Anthial** [comment]
> I think it works as a first draft but I still think it needs some styling work

100%
It doesn't even have a proper mobile view yet!

**Comment by Anthial** [comment]
Yay! Now we're also dealing with #10! 
Gimme a basic non-details/trivia view and I'll implement the router stuff 😁

**Comment by Anthial** [comment]
Closed until we have at least one more view so that I can do the required router work.

**Pull request closed without merging**
